grub2-grubenv-in-btrfs-header
GRUB cannot write Btrfs file systems from the bootloader, so it cannot
modify values set from userspace (e.g. "next_entry" set by grub2-once).
As a workaround use the Btrfs header to store known data of the GRUB environment
block.

v2: export env_block and make sure to use the device of grubenv

v3:
  * Use xcalloc for overflow check and return NULL when it would
    occur.

v4:
  * Fix gcc error with CFLAGS=-Og

  ../util/grub-editenv.c: In function ‘read_envblk_fs’:
  ../util/grub-editenv.c:172:14: error: ‘sz’ may be used uninitialized [-Werror=maybe-uninitialized]
    172 |           sz <<= GRUB_DISK_SECTOR_BITS;
  ../util/grub-editenv.c:155:16: note: ‘sz’ was declared here
    155 |       int off, sz;
        |                ^~
  cc1: all warnings being treated as errors